### ISSUE TITLE
401 : Invalid credentials

### ISSUE THREAD

**Issue by rrraf** [pironic/ourgroceries_restapi#1]
hi,
thanks for the code. i'm very interested in using this with Google Home (via IFTTT).
i'm having an invalid credentials error (401).
email, password and listId should be correct. teamId is copied from page source of "ourgroceries.com" directly. cookie.txt is correctly created.
issue happens from POST and GET method (with apikey).

**Comment by pironic** [comment]
An invalid credential error is because something provided to the ourgroceries service did not like what you provided it. this is likely the team and list id's. In the config you'll need to make sure these are populated with the scrapped values from a valid request via the website. To find them you'll want to open https://www.ourgroceries.com/your-lists/ and check the source of that page. there are 2 variables saved in the source that you need that you can find by pressing ctrl+f or cmd+f (Depending on your OS). You are looking for g_teamId and g_shoppingLists. The list Id is the id for the list you want to add items to via IFTTT (If you have more than one). 
![image](https://user-images.githubusercontent.com/541154/26836484-33ea528c-4a98-11e7-8750-ea1ad3f8d63e.png)


Once you set those two variables in the config.php and your user/pass for the app, it should work. Let me know if you have any trouble and i'll do my best to help you out.

**Comment by pironic** [comment]
One additional note... now that IFTTT has allowed maker profiles, i plan to make a universal url and recipe that anyone can add items to ourgroceries with. If you want to wait about a week i'll have that up and ready. Avoid the heartache of trying to troubleshoot some shitty code :P

**Comment by rrraf** [comment]
thanks for the quick reply. unfortunately the variables were already the correct ones.
the only difference i see is that i have more than one shopping list... 

good news for IFTTT... but now i "need" to know why it doesn't work ;-)

**Comment by rrraf** [comment]
i tried another php server and it works. i guess my server has some limitation/protection. i'm sorry i made you lose time. thanks a lot for the support... and for the code !!!
